export interface Tinder {
  url: string
  discount: string
  naming: string
  price: string
  priceDiscount: string
  image: string
}

export const tinders: Tinder[] = [
  {
    url: '#',
    discount: 'Еще 23 часа скидка',
    naming: 'Автомобильное ЗУ Pero AC06 черный',
    price: '850 ₽',
    priceDiscount: '1 150 ₽',
    image: '../pages/main-page/components/action-tinder/images/adapter.jpg',
  },
  {
    url: '#',
    discount: 'Выгодно в комплекте',
    naming: 'Сушильная машина Gorenje DNS92 белый',
    price: '89 999 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/stiralka.jpg',
  },
  {
    url: '#',
    discount: 'Еще 22 часа скидка',
    naming: '6.67" Смартфон HUAWEI P60 Pro 256 ГБ белый',
    price: '59 999 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/phone.jpg',
  },
  {
    url: '#',
    discount: 'Выгодно в комплекте',
    naming: 'Сушильная машина Gorenje DNA82 белый',
    price: '59 999 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/stiralka2.jpg',
  },
  {
    url: '#',
    discount: 'Выгодно в комплекте',
    naming: 'Микроволновая печь Gorenje MO17E1S серебристый',
    price: '5 999 ₽',
    priceDiscount: '6 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/microwave.jpg',
  },
  {
    url: '#',
    discount: 'Еще 1 день скидка',
    naming: 'Мойка высокого давления Karcher K 3 EU',
    price: '8 499 ₽',
    priceDiscount: '9 599 ₽',
    image: '../pages/main-page/components/action-tinder/images/cleaner.jpg',
  },
  {
    url: '#',
    discount: 'Еще 1 день скидка',
    naming: 'Холодильник Side by Side  Gorenje NRR9185EAXLWD серебристый',
    price: '88 499 ₽',
    priceDiscount: '99 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/holodilnik.jpg',
  },
  {
    url: '#',
    discount: 'Еще 1 день скидка',
    naming: 'IP-камера Dahua DH-IPC-HFW2449SP-S-IL-0280B',
    price: '8 699 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/camera.jpg',
  },
  {
    url: '#',
    discount: 'Еще 1 день скидка',
    naming: 'Фитнес-браслет HUAWEI Band 8',
    price: '1 799 ₽',
    priceDiscount: '1 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/smartband.jpg',
  },
  {
    url: '#',
    discount: 'Еще 2 дня скидка',
    naming: 'Телефон беспроводной (DECT) Panasonic KX-TG1611RUW',
    price: '3 499 ₽',
    priceDiscount: '3 699 ₽',
    image: '../pages/main-page/components/action-tinder/images/homephone.jpg',
  },
  {
    url: '#',
    discount: 'Еще 2 дня скидка',
    naming: 'Наушники TWS HUAWEI Freebuds 5i черный',
    price: '4 499 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/airpods.jpg',
  },
  {
    url: '#',
    discount: 'Еще 4 дня скидка',
    naming: '34" Монитор HUAWEI MateView GT ZQE-CBA черный',
    price: '38 999 ₽',
    priceDiscount: '45 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/monitor.jpg',
  },
  {
    url: '#',
    discount: 'Еще 4 дня скидка',
    naming: '6.7" Смартфон Apple iPhone 15 Pro Max 256 ГБ серый',
    price: '139 899 ₽',
    priceDiscount: '158 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/iphone.jpg',
  },
  {
    url: '#',
    discount: 'Еще 4 дня скидка',
    naming: '10.2" Планшет Apple iPad (9th Gen) Wi-Fi 64 ГБ серый',
    price: '34 199 ₽',
    priceDiscount: '37 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/ipad.jpg',
  },
  {
    url: '#',
    discount: 'Еще 4 дня скидка',
    naming: '15.6" Ноутбук ASUS TUF Gaming F15 FX507ZC4-HN009 серый',
    price: '78 999 ₽',
    priceDiscount: '88 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/notebook1.jpg',
  },
  {
    url: '#',
    discount: 'Еще 4 дня скидка',
    naming: '15.6" Ноутбук ASUS TUF Gaming A15 FA507NU-LP101 серый',
    price: '89 999 ₽',
    priceDiscount: '99 999 ₽',
    image: '../pages/main-page/components/action-tinder/images/notebook2.jpg',
  },
  {
    url: '#',
    discount: 'Выгодно в комплекте',
    naming: 'Стиральная машина Gorenje WNS94ACIS белый',
    price: '79 999 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/stiralka4.jpg',
  },
  {
    url: '#',
    discount: 'Выгодно в комплекте',
    naming: 'Холодильник с морозильником  Gorenje NRK6201ES4 серебристый',
    price: '48 999 ₽',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/holodilnik2.jpg',
  },
  {
    url: '#',
    discount: 'Горячие акции, которые скоро закончатся',
    naming: '',
    price: '',
    priceDiscount: '',
    image: '../pages/main-page/components/action-tinder/images/last-icon.png',
  },
]
